import sqlite3
conn= sqlite3.connect("test4.db")
conn.execute("create table customer_login(cid integer, password varchar(20),primary key(cid, password));")
conn.execute("create table customer(cid integer primary key, cname varchar(20), address varchar(30), phonenumber integer, email varchar(20),bkartid integer, skartid integer, foreign key(cid) references customer_login(cid));")
conn.execute("create table product(pid integer, pname varchar(20), brand varchar(20), price integer, description varchar(30), review integer,check(review <= 5));")
conn.execute("create table sold_items(bkartid integer, transid integer,pid integer, primary key(bkartid,transid,pid), foreign key (pid) references product(pid), foreign key(bkartid) references customer(bkartid));")
conn.execute("create table buy_kart(bkartid integer, cid integer, transid integer, pid integer, pname varchar(30), total_cost integer, primary key(bkartid, cid, transid),foreign key (cid) references customer(cid),foreign key (bkartid) references sold_items(bkartid),foreign key(transid) references sold_items(transid));")
conn.execute("create table payment(transid integer, kartid integer, cid integer, total_cost integer, payment_method varchar(10), primary key(transid, kartid, cid), foreign key(transid) references sold_items(transid), foreign key(cid) references customer(cid));")
conn.execute("create table sell_kart(skartid integer, cid integer, pid integer,pname integer,brand varchar(20),size integer,price integer,description varchar(30));")
conn.execute("create table admin_login(aid integer,password integer,primary key(aid,password));")
conn.execute("create table admin(aid integer, aname integer, phone_number integer,email varchar(20));")


conn.execute("insert into customer_login values(1,'11');")
conn.execute("insert into customer_login values(2,'22');")
conn.execute("insert into customer_login values(3,'33');")
conn.execute("insert into customer_login values(4,'44');")
conn.execute("insert into customer_login values(5,'55');")
conn.execute("insert into customer values(1,'Aditya','Ranchi','1111111111','tysonbroter@gmail.com','101','201');")
conn.execute("insert into customer values(2,'Suneet','France','2222222222','suneet@gmail.com','102','202');")
conn.execute("insert into customer values(3,'Khera','Delhi','3333333333','khera@gmail.com','103','203');")
conn.execute("insert into customer values(4,'Chatterjee','Kanpur','4444444444','chatterjee@gmail.com','104','204');")
conn.execute("insert into customer values(5,'Eldon','Udupi','5555555555','eldon@gmail.com','105','205');")
conn.execute("insert into product values(11,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(12,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(13,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(14,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(15,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(16,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(17,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(18,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(19,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(20,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(21,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(22,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(23,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(24,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(25,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(26,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(27,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(28,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(29,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(30,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(31,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(32,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(33,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(34,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(35,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(36,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(37,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(38,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(39,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(40,'casio watch','casio','10000','beauty and the beast',4);")

