import sqlite3
conn= sqlite3.connect("test7.db")
conn.execute("create table customer_login(cid integer, password varchar(20),primary key(cid, password));")
conn.execute("create table customer(cid integer primary key, cname varchar(20), address varchar(30),
             phonenumber integer, email varchar(20),bkartid integer, skartid integer, foreign key(cid) references customer_login(cid));")
conn.execute("create table product(pid integer, pname varchar(20), brand varchar(20),
             price integer, description varchar(30), review integer,check(review <= 5));")
conn.execute("create table sold_items(bkartid integer, transid integer,pid integer,
             primary key(bkartid,transid,pid), foreign key (pid) references product(pid), foreign key(bkartid) references customer(bkartid));")
conn.execute("create table buy_kart(bkartid integer, cid integer, transid integer,
             pid integer, pname varchar(30), total_cost integer, primary key(bkartid, cid, transid),foreign key (cid) references customer(cid),foreign key (bkartid) references sold_items(bkartid),foreign key(transid) references sold_items(transid));")
conn.execute("create table payment(transid integer, bkartid integer, cid integer,
             total_cost integer, payment_method varchar(10), primary key(transid, bkartid, cid), foreign key(transid) references sold_items(transid), foreign key(cid) references customer(cid));")
conn.execute("create table sell_kart(skartid integer, cid integer, pid integer,
             pname integer,brand varchar(20),size integer,price integer,description varchar(30));")
conn.execute("create table admin_login(aid integer,password integer,
             primary key(aid,password));")
conn.execute("create table admin(aid integer, aname integer, phone_number integer,
             email varchar(20));")
conn.execute("insert into customer_login values(1,'11');")
conn.execute("insert into customer_login values(2,'22');")
conn.execute("insert into customer_login values(3,'33');")
conn.execute("insert into customer_login values(4,'44');")
conn.execute("insert into customer_login values(5,'55');")
conn.execute("insert into customer values(1,'Aditya','Ranchi','1111111111','tysonbrother@gmail.com','101','201');")
conn.execute("insert into customer values(2,'Suneet','France','2222222222','suneetrk@gmail.com','102','202');")
conn.execute("insert into customer values(3,'Khera','Delhi','3333333333','khera@gmail.com','103','203');")
conn.execute("insert into customer values(4,'Chatterjee','Kanpur','4444444444','chatterjee@gmail.com','104','204');")
conn.execute("insert into customer values(5,'Eldon','Udupi','5555555555','eldon@gmail.com','105','205');")
conn.execute("insert into product values(11,'casio watch','casio','10000','beauty and the beast',4);")
conn.execute("insert into product values(12,'casio clock','casio','4800','matt black',4);")
conn.execute("insert into product values(13,'lamp','philips','1000','barbie',4);")
conn.execute("insert into product values(14,'car','bwm','1900000','white',4);")
conn.execute("insert into product values(15,'car','mercedes','2000000','pink',4);")
conn.execute("insert into product values(16,'car','nano','100000','yellow',4);")
conn.execute("insert into product values(17,'car','swift','500000','barbie',4);")
conn.execute("insert into product values(18,'car','scorpio','10000000','suv',4);")
conn.execute("insert into product values(19,'lamp','ajanta','2000','bluW',4);")
conn.execute("insert into product values(20,'lamp','philips','4000','GREY',4);")
conn.execute("insert into product values(21,'clothing','hnm','3000','hoodie',4);")
conn.execute("insert into product values(22,'clothing','van huesen','4000','shirt',4);")
conn.execute("insert into product values(23,'clothing','levis','4000','jeans',4);")
conn.execute("insert into product values(24,'clothing','zara','8000','kurta',4);")
conn.execute("insert into product values(25,'clothig','adidas','9000','tracksuit',4);")
conn.execute("insert into product values(26,'phone','samsung','30000','galaxy y',4);")
conn.execute("insert into product values(27,'phone','samsung','40000','a90',4);")
conn.execute("insert into product values(28,'phone','apple','60000','iphonexr',4);")
conn.execute("insert into product values(29,'phone','nokia','4500','nokia3208',4);")
conn.execute("insert into product values(30,'phone','lg','14000','GREY',4);")
conn.execute("insert into product values(31,'shoes','adidas','14000','black',4);")
conn.execute("insert into product values(32,'shoes','nike','9000','GREY',4);")
conn.execute("insert into product values(33,'shoes','nike','13000','green',4);")
conn.execute("insert into product values(34,'shoes','reebok','14000','blue',4);")
conn.execute("insert into product values(35,'shoes','puma','10000','GREY',4);")
conn.execute("insert into product values(36,'homeappliances','pigeon','3000','mixie',4);")
conn.execute("insert into product values(37,'homeappliances','pigeon','5000','pan',4);")
conn.execute("insert into product values(38,'homeappliances','qwar','9000','vaccuum cleaner',4);")
conn.execute("insert into product values(39,'homeappliances','rama','3000','plate set',4);")
conn.execute("insert into product values(40,'homeappliances','rama','15000','washing machine',4);")
conn.execute("insert into product values(41,'homeappliances','tupperware','500','bottle',4);")
conn.execute("insert into product values(42,'homeappliances','pigeon','8000','knifeset',4);")
conn.execute("insert into product values(43,'poster','art','200','harrypotter',4);")
conn.execute("insert into product values(44,'poster','art','300','doraemon',4);")
conn.execute("insert into product values(45,'poster','art','600','onepunchman',4);")
conn.execute("insert into product values(46,'poster','art','300','ben10',4);")
conn.execute("insert into product values(47,'poster','art','150','motivational',4);")
conn.execute("insert into product values(48,'poster','art','300','catchphrase',4);")
conn.execute("insert into sold_items values(101,301,44);")
conn.execute("insert into sold_items values(102,302,15);")
conn.execute("insert into sold_items values(103,303,35);")
conn.execute("insert into sold_items values(104,304,40);")
conn.execute("insert into sold_items values(105,305,36);")
conn.commit()
